version: '3.2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mmrsdevwp
      MYSQL_DATABASE: mmrsdevwp
      MYSQL_USER: mmrsdev
      MYSQL_PASSWORD: mmrsdevdckrprttype

  wordpress:
    depends_on:
      - db
    image: wordpress:5.5-php7.3-apache
    ports:
      - "8051:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mmrsdev
      WORDPRESS_DB_PASSWORD: mmrsdevdckrprttype
      WORDPRESS_CONFIG_EXTRA: define('SCRIPT_DEBUG', true);

    working_dir: /var/www/html/
    volumes:
      - ./wp-content:/var/www/html/wp-content
volumes:
  db_data:
